services:
  - type: web
    name: ai-project-backend
    env: python
    region: singapore
    plan: free
    branch: main
    
    # === Cấu hình build & chạy (Đã chính xác) ===
    rootDir: ./backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port 10000"

    # === SỬA LẠI PHẦN NÀY ===
    # Khai báo các key mà Render sẽ hỏi bạn trên giao diện web
    envVars:
      - key: GOOGLE_API_KEY
      - key: SQLALCHEMY_DATABASE_URL
      - key: SECRET_KEY