services:
  # Service cho Backend
  - type: web
    name: ai-project-backend
    runtime: python
    region: singapore
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: SQLALCHEMY_DATABASE_URL
        fromDatabase:
          name: ai-project-db
          property: connectionString
      - key: GOOGLE_API_KEY
        value: AIzaSyALQkMTzmciT70p_TzGHxGVTZNrp38AYlQ # Key API mới nhất của bạn
      - key: SECRET_KEY
        generateValue: true # Render sẽ tự động tạo một chuỗi bí mật an toàn
      - key: PYTHONPATH
        value: /opt/render/project/src/backend # Thêm PYTHONPATH để Python tìm thấy module 'app'

databases:
  # Database cho dự án
  - name: ai-project-db
    region: singapore
    plan: free